name: CI Run
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
jobs:
  trigger_ci_by_event:
    runs-on: ubuntu-latest
    steps:
      - name: Log Event
        run: echo "${{ toJson(github.event) }}"